const { Edit_User_PROFILE, RESET_PASSWORD, ADD_ADDRESS, REMOVE_ADDRESS, GET_STORE_CATEGORIES, GET_ALL_PRODUCT, GET_STORE_BY_ID,
    TOP_RATED_PRODUCTS, STORE_TOP_RATED_PRODUCTS, STORE_PRODUCTS, PRODUCT_BY_STORE_AND_CATEGORY, PRODUCT_SEARCH, ADD_PRODUCT_TO_WISHLIST, DELETE_PRODUCT_FROM_WISHLIST,
    GET_USER_WISHLIST, GET_ALL_STORE, GET_CURRENT_USER, GET_ALL_ACTIVE_ADVERTISMENTS} = require("../../endPoints/endPoints");

module.exports = [Edit_User_PROFILE, RESET_PASSWORD, ADD_ADDRESS, REMOVE_ADDRESS, GET_STORE_CATEGORIES, GET_ALL_PRODUCT, GET_STORE_BY_ID,
    TOP_RATED_PRODUCTS, STORE_TOP_RATED_PRODUCTS, STORE_PRODUCTS, PRODUCT_BY_STORE_AND_CATEGORY, PRODUCT_SEARCH, ADD_PRODUCT_TO_WISHLIST, DELETE_PRODUCT_FROM_WISHLIST,
    GET_USER_WISHLIST, GET_ALL_STORE, GET_CURRENT_USER, GET_ALL_ACTIVE_ADVERTISMENTS
];