const ADD_ADMIN = "admin:ADD_ADMIN";
const ADMIN_SIGNIN = "admin:ADMIN_SIGNIN";
const UPDATE_ADMIN = "admin:UPDATE_ADMIN";
const DELETE_ADMIN = "admin:DELETE_ADMIN";
const GET_ALL_ADMIN = "admin:GET_ALL_ADMIN";
const GET_CURRENT_ADMIN = "admin:GET_CURRENT_ADMIN";

const ADD_CATEGORY = "category:ADD_CATEGORY";
const UPDATE_CATEGORY = "category:UPDATE_CATEGORY";
const DELETE_CATEGORY = "category:DELETE_CATEGORY";
const GET_ALL_CATEGORY = "category:GET_ALL_CATEGORY";

const ADD_PRODUCT = "product:ADD_PRODUCT";
const UPDATE_PRODUCT = "product:UPDATE_PRODUCT";
const DELETE_PRODUCT = "product:DELETE_PRODUCT";
const GET_ALL_PRODUCT = "product:GET_ALL_PRODUCT";

const GET_PRODUCT_BY_ID = "product:GET_PRODUCT_BY_ID";


const ADD_STORE = "store:ADD_STORE";
const UPDATE_STORE = "store:UPDATE_STORE";
const DELETE_STORE = "store:DELETE_STORE";
const GET_ALL_STORE = "store:GET_ALL_STORE";

const Edit_User_PROFILE = "user:Edit_User_PROFILE";
const RESET_PASSWORD = "user:RESET_PASSWORD";
const ADD_ADDRESS = "user:ADD_ADDRESS";
const REMOVE_ADDRESS= "user:REMOVE_ADDRESS";
const GET_ALL_USERS = "user:GET_ALL_USERS";
const GET_CURRENT_USER = "user:GET_CURRENT_USER";
const GET_STORE_CATEGORIES = "store:GET_STORE_CATEGORIES";
const GET_STORE_BY_ID = "store:GET_STORE_BY_ID";
const TOP_RATED_PRODUCTS = "product:TOP_RATED_PRODUCTS";
const STORE_TOP_RATED_PRODUCTS = "product:STORE_TOP_RATED_PRODUCTS";
const STORE_PRODUCTS = "product:STORE_PRODUCTS";
const PRODUCT_BY_STORE_AND_CATEGORY = "product:PRODUCT_BY_STORE_AND_CATEGORY";
const PRODUCT_SEARCH = "product:PRODUCT_SEARCH";
const ADD_PRODUCT_TO_WISHLIST = "wishlist:ADD_PRODUCT_TO_WISHLIST"
const DELETE_PRODUCT_FROM_WISHLIST = "wishlist:DELETE_PRODUCT_FROM_WISHLIST"
const GET_USER_WISHLIST =  "wishlist:GET_USER_WISHLIST"
const RECENT_CATEGORIES = "category:RECENT_CATEGORIES";
const RECENT_STORES = "store:RECENT_STORES";
const COUNT_USERS_CATEGORIES_STORES = "store:COUNT_USERS_CATEGORIES_STORES";
const GET_ADMIN_BY_ID = "admin:GET_ADMIN_BY_ID"
const GET_CATEGORY_BY_ID = "category:GET_CATEGORY_BY_ID"



const ADD_ADVERTISMENT = "advertisment:ADD_ADVERTISMENT";
const UPDATE_ADVERTISMENT = "advertisment:UPDATE_ADVERTISMENT";
const DELETE_ADVERTISMENT = "advertisment:DELETE_ADVERTISMENT";
const GET_ALL_ADVERTISMENTS = "advertisment:GET_ALL_ADVERTISMENTS";
const GET_ALL_ACTIVE_ADVERTISMENTS = "advertisment:GET_ALL_ACTIVE_ADVERTISMENTS";
const GET_ADVERTISMENTS_BY_ID = "advertisment:GET_ADVERTISMENTS_BY_ID";


module.exports = {
    ADD_ADMIN,
    ADMIN_SIGNIN,
    UPDATE_ADMIN,
    DELETE_ADMIN,
    GET_ALL_ADMIN,
    GET_PRODUCT_BY_ID,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    GET_ALL_CATEGORY,
    ADD_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    GET_ALL_PRODUCT,
    ADD_STORE,
    UPDATE_STORE,
    DELETE_STORE,
    GET_ALL_STORE,
    Edit_User_PROFILE,
    RESET_PASSWORD,
    ADD_ADDRESS,
    REMOVE_ADDRESS,
    GET_ALL_USERS,
    GET_STORE_CATEGORIES,
    GET_STORE_BY_ID,
    TOP_RATED_PRODUCTS,
    STORE_TOP_RATED_PRODUCTS,
    STORE_PRODUCTS,
    PRODUCT_BY_STORE_AND_CATEGORY,
    PRODUCT_SEARCH,
    ADD_PRODUCT_TO_WISHLIST,
    DELETE_PRODUCT_FROM_WISHLIST,
    GET_USER_WISHLIST,
    GET_CURRENT_USER,
    GET_CURRENT_ADMIN,
    RECENT_CATEGORIES,
    RECENT_STORES,
    COUNT_USERS_CATEGORIES_STORES,
    GET_ADMIN_BY_ID,
    GET_CATEGORY_BY_ID,
    ADD_ADVERTISMENT,
    UPDATE_ADVERTISMENT,
    DELETE_ADVERTISMENT,
    GET_ALL_ADVERTISMENTS,
    GET_ALL_ACTIVE_ADVERTISMENTS,
    GET_ADVERTISMENTS_BY_ID,
}